import { db } from '@/db';
import { sweets } from '@/db/schema';

async function main() {
    const sampleSweets = [
        {
            name: 'Dark Chocolate Truffle',
            description: 'Rich, velvety dark chocolate ganache dusted with cocoa powder. A luxurious treat for chocolate lovers.',
            price: 8.99,
            stockQuantity: 25,
            imageUrl: 'https://via.placeholder.com/300x300?text=Dark+Chocolate+Truffle',
            category: 'Chocolate',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Milk Chocolate Bar',
            description: 'Classic smooth and creamy milk chocolate bar. Perfect for everyday snacking.',
            price: 3.49,
            stockQuantity: 40,
            imageUrl: 'https://via.placeholder.com/300x300?text=Milk+Chocolate+Bar',
            category: 'Chocolate',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'White Chocolate Raspberry',
            description: 'Sweet white chocolate infused with tangy raspberry pieces. A delightful fruity combination.',
            price: 6.99,
            stockQuantity: 15,
            imageUrl: 'https://via.placeholder.com/300x300?text=White+Chocolate+Raspberry',
            category: 'Chocolate',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Strawberry Gummy Bears',
            description: 'Soft, chewy gummy bears bursting with sweet strawberry flavor. Kids and adults love them!',
            price: 4.99,
            stockQuantity: 30,
            imageUrl: 'https://via.placeholder.com/300x300?text=Strawberry+Gummy+Bears',
            category: 'Gummy',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Sour Worms',
            description: 'Tangy, sour-coated gummy worms in assorted fruit flavors. Pucker up for this sweet and sour sensation!',
            price: 3.99,
            stockQuantity: 0,
            imageUrl: 'https://via.placeholder.com/300x300?text=Sour+Worms',
            category: 'Gummy',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Watermelon Slices',
            description: 'Juicy watermelon-flavored gummy slices with a sugar coating. Refreshing and fun!',
            price: 4.49,
            stockQuantity: 20,
            imageUrl: 'https://via.placeholder.com/300x300?text=Watermelon+Slices',
            category: 'Gummy',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Peppermint Hard Candy',
            description: 'Classic peppermint hard candies that melt slowly on your tongue. Fresh and cooling.',
            price: 2.49,
            stockQuantity: 50,
            imageUrl: 'https://via.placeholder.com/300x300?text=Peppermint+Hard+Candy',
            category: 'Hard Candy',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Butterscotch Discs',
            description: 'Traditional butterscotch hard candies with a rich, buttery flavor. A timeless favorite.',
            price: 2.99,
            stockQuantity: 35,
            imageUrl: 'https://via.placeholder.com/300x300?text=Butterscotch+Discs',
            category: 'Hard Candy',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Cinnamon Balls',
            description: 'Spicy cinnamon-flavored hard candies with a fiery kick. Not for the faint of heart!',
            price: 2.79,
            stockQuantity: 10,
            imageUrl: 'https://via.placeholder.com/300x300?text=Cinnamon+Balls',
            category: 'Hard Candy',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Rainbow Swirl Lollipop',
            description: 'Colorful rainbow swirl lollipop on a stick. A beautiful and tasty treat for all ages.',
            price: 1.99,
            stockQuantity: 45,
            imageUrl: 'https://via.placeholder.com/300x300?text=Rainbow+Swirl+Lollipop',
            category: 'Lollipop',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Cherry Lollipop',
            description: 'Sweet cherry-flavored lollipop with a bright red color. A classic favorite!',
            price: 1.49,
            stockQuantity: 5,
            imageUrl: 'https://via.placeholder.com/300x300?text=Cherry+Lollipop',
            category: 'Lollipop',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Blue Raspberry Pop',
            description: 'Tangy blue raspberry lollipop that turns your tongue blue. Fun and delicious!',
            price: 1.79,
            stockQuantity: 28,
            imageUrl: 'https://via.placeholder.com/300x300?text=Blue+Raspberry+Pop',
            category: 'Lollipop',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Caramel Chews',
            description: 'Soft, chewy caramel candies that stick to your teeth. Rich and buttery flavor in every bite.',
            price: 5.49,
            stockQuantity: 22,
            imageUrl: 'https://via.placeholder.com/300x300?text=Caramel+Chews',
            category: 'Candy',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Fruit Punch Taffy',
            description: 'Stretchy, flavorful fruit punch taffy with a tropical twist. Chewy and fun to eat!',
            price: 4.29,
            stockQuantity: 18,
            imageUrl: 'https://via.placeholder.com/300x300?text=Fruit+Punch+Taffy',
            category: 'Candy',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Licorice Twists',
            description: 'Classic black licorice twists with an authentic anise flavor. Love it or hate it candy!',
            price: 3.89,
            stockQuantity: 0,
            imageUrl: 'https://via.placeholder.com/300x300?text=Licorice+Twists',
            category: 'Candy',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
    ];

    await db.insert(sweets).values(sampleSweets);
    
    console.log('✅ Sweets seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});